### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by releu**
Screen Shot 2013-02-23 at 3 37 48 PM

Comments and suggestions are appreciated.

### CODE REVIEW

**Comment by killthekitten** [comment]
Lot of grey colors/borders, don't you think so?

**Comment by releu** [comment]
Yeah..

**Comment by releu** [comment]
Screen Shot 2013-02-23 at 4 55 45 PM

**Comment by releu** [comment]
Screen Shot 2013-02-25 at 11 23 51 PM

**Comment by releu** [comment]
Screen Shot 2013-02-25 at 11 38 27 PM

**Comment by releu** [comment]
Screen Shot 2013-02-25 at 11 57 23 PM

**Comment by releu** [comment]
Screen Shot 2013-02-26 at 4 45 59 PM

**Comment by releu** [comment]
Screen Shot 2013-03-28 at 11 43 46 PM

**Comment by kirs** [comment]
Looks like a github copy :( Maybe we need to find a real designer to make it better?

**Comment by killthekitten** [comment]
@kirs :+1:

**Comment by releu** [comment]
Head? Yeah. It will be changed.
At first I wanna make and test handy interfaces for each features, then change design to something new or pay for it.

**Comment by releu** [comment]
Screen Shot 2013-03-31 at 11 22 03 AM

**Comment by releu** [comment]
Screen Shot 2013-03-31 at 11 53 01 PM

**Comment by releu** [comment]
Screen Shot 2013-04-08 at 9 12 26 PM
Screen Shot 2013-04-08 at 9 12 13 PM
Screen Shot 2013-04-08 at 9 12 18 PM

**Comment by releu** [comment]
Screen Shot 2013-04-08 at 9 27 04 PM

**Comment by skopp** [comment]
How about a day/night mode toggle?

**Comment by releu** [comment]
Hmm.. Can you suggest a good example?

**Comment by makaroni4** [comment]
@skopp great idea I think. Do you think it should be in settings or like a toggle control on every page?

**Comment by skopp** [comment]
re: https://github.com/gistflow/gistflow/pull/232#issuecomment-19197433

Day mode 
Night mode

**Comment by releu** [comment]
Yeah. Toggle view :+1:. Thanks :)

**Comment by makaroni4** [comment]
I think a good way to do it – browser extension, because it will work for every website, not only Gistflow.

https://chrome.google.com/webstore/detail/high-contrast/djcfdncoelnlbldjfhinnjlhdjlikmph for example

**Comment by skopp** [comment]
@makaroni4 Personally, I'd prefer a globally visible (albeit somewhere 'out-the-way') button.

**Comment by skopp** [comment]
Sure, I actually use [Hacker Vision](https://chrome.google.com/webstore/detail/hacker-vision/fommidcneendjonelhhhkmoekeicedej) - but in general I just try not to have too many extensions installed. Also: I (and I imagine quite a few people) use multiple browsers, not just Chrome! E.g Firefox, Icedragon, Opera, Maxthon, Chromium, Waterfox etc.

**Pull request closed without merging**
