### PR TITLE
Quick and dirty way to run gistflow localy

### PR DESCRIPTION
**Pull request by killthekitten**
It happened so, that in development mode for login is used SessionController#create. And it fails. It takes some time to understand the reason of failure, load console and create new user with token.

So I decided to introduce task which creates ummm... "valid" user. 

It's quick and dirty, though it's temporary. I hope someday SessionController will be reviewed and refactored.

### CODE REVIEW

**Comment by releu** [comment]
let's just fill in seeds.rb with FactoryGirl.create(:user, username: 'releu') and use rake db:setup to start

**Comment by releu** [comment]
but that's ugly... we need to create a new app and use their keys as default dev keys

**Comment by makaroni4** [comment]
:+1: @releu, I think this is where it should be.

@killthekitten could you please move it to seed?

**Comment by killthekitten** [comment]
Yes, great idea :+1:

**Comment by releu** [comment]
Client ID `927a0bef13ad23c58248`
Client Secret `8e5e044e3b37ddbb425c725d001b489e7ec28845`
URL `http://gistflow.dev`
Callback URL `http://gistflow.dev/auth/github/callback`

**Comment by killthekitten** [comment]
@releu isn't it too much?

**Comment by makaroni4** [comment]
@releu make it even clearer :smile:

These are credentials of http://gistflow.dev app :smile:

So you don't even need seed

**Comment by killthekitten** [comment]
You're using Pow, huh?

**Comment by releu** [comment]
Yep

**Comment by killthekitten** [comment]
Brilliant. Should I mention Pow/Powder in Readme? And what to do with previous two commits? Force them, or create new PR, or nothing?

**Comment by releu** [comment]
Yes, pow should be mentioned. I won't worry about reverts or forcing them.

**Comment by killthekitten** [comment]
Can't remember why I'm feeling so negative about Pow... no chance...

**Pull request merged**
