### PR TITLE
Update notifications display

### PR DESCRIPTION
**Pull request by killthekitten**
Notifications are completely unuseful, currently. I can't just look through them and understand which posts do I need to visit. This PR fixes it by change from displaying post id to displaying post title.

### CODE REVIEW

**Comment by killthekitten** [comment]
Oh shi. I wanted to create separate PRs. But... nevermind. OK

**Comment by releu** [comment]
You can see post's title when hover link to it. If we just render it, notifications will not be organized because of different widths.

I have another solution for menu #218

**Comment by killthekitten** [comment]
@releu #218 is great indeed, I agree with it.

But notifications aren't usable right now, they are just a mess of letters and numbers. Don't you agree with me?

 I think the first step in reorganizing is to make user able to look through titles without moving cursor. The second can be grouping by notification type

**Comment by releu** [comment]
I'll try to do something for it

**Comment by killthekitten** [comment]
:+1:

**Pull request closed without merging**
